### ISSUE TITLE
question: how does this relate to org-pomodoro?

### ISSUE THREAD

**Issue by japhir** [alphapapa/hammy.el#1]
Hi! This looks fun! It looks like it would be a more customizable version of [org-pomodoro](https://github.com/marcinkoziej/org-pomodoro), right? I was just wondering what you intend to make (and potentially point you to org-pomodoro if you hadn't heard of it yet) :).

**Comment by alphapapa** [comment]
Hello,

Of course, I'm well aware of org-pomodoro, as it's been around for many years.  I intend to make a counterpart package, `org-hammy`, to integrate Hammy with Org clocking, which will be an alternative to org-pomodoro.
