### ISSUE TITLE
How to call hammy-next from terminal using emacsclient?

### ISSUE THREAD

**Issue by Rickyfs** [alphapapa/hammy.el#14]
it is very useful to be able to hammy-next from terminal or adding on click handlers on notifications.  For example with org-pomodoro to finish task its `emacsclient -e '(org-pomodoro-finished)'`

Using hammy I expected it to be done with `emacsclient -e '(hammy-next)'` however it requires hammy argument (different behaviour than calling hammy-next from inside emacs). Trying `emacsclient -e '(hammy-next hammy-active)'`  throws error in terminal "ERROR: Wrong type argument: hammy" (open details below). 

<details>
 <summary>Long error</summary>

*ERROR*: Wrong type argument: hammy, (#s(hammy "CUSTOM ⅓-time" "Breaks that are ⅓ as long as the last work interval." ((#s(hammy-interval "Work" "" nil "90 minutes" ((lambda (hammy) (progn (ignore hammy) (hammy-announce hammy "Starting work time (advance to break when ready).") (hammy-notify hammy "Starting work time (advance to break when ready).")))) nil ((lambda (hammy) (if (listp (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 13))) nil (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (let* ((v hammy)) (aset v 13 (list (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 13))))))) (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (let* ((v hammy)) (aset v 13 (let* ((vlist (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 13)))) (if (memql --cl-cancel-reminder-- vlist) vlist (cons --cl-cancel-reminder-- vlist)))))) (let ((tail fns)) (while tail (let ((fn (car tail))) (funcall fn hammy) (setq tail (cdr tail))))) (let ((delay-secs (funcall --cl-duration-- delay))) (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (let* ((v hammy) (p (if (and nil (not (eq nil 'eq))) (assoc 'reminder (aref v 11) nil) (assq 'reminder (aref v 11)))) (v (run-with-timer delay-secs delay-secs #'(lambda (hammy) (let ((tail fns)) (while tail (let ((fn (car tail))) (funcall fn hammy) (setq tail (cdr tail)))))) hammy))) (progn (if p (setcdr p v) (aset v 11 (cons (setq p (cons 'reminder v)) (aref v 11)))) v)))) (if (listp (progn (or (progn (and (memq (type-of (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))) cl-struct-hammy-interval-tags) t)) (signal 'wrong-type-argument (list 'hammy-interval (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))))) (aref (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6)) 6))) nil (progn (or (progn (and (memq (type-of (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))) cl-struct-hammy-interval-tags) t)) (signal 'wrong-type-argument (list 'hammy-interval (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))))) (let* ((v (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6)))) (aset v 6 (list (progn (or (progn (and (memq (type-of (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))) cl-struct-hammy-interval-tags) t)) (signal 'wrong-type-argument (list 'hammy-interval (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))))) (aref (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6)) 6))))))) (progn (or (progn (and (memq (type-of (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))) cl-struct-hammy-interval-tags) t)) (signal 'wrong-type-argument (list 'hammy-interval (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))))) (let* ((v (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6)))) (aset v 6 (let* ((vlist (progn (or (progn (and (memq (type-of (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))) cl-struct-hammy-interval-tags) t)) (signal 'wrong-type-argument (list 'hammy-interval (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6))))) (aref (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 6)) 6)))) (if (memql --cl-cancel-reminder-- vlist) vlist (cons --cl-cancel-reminder-- vlist))))))))) (25846 24381 457221 108000) (25846 24665 306969 2000))) 0 (0 2 . [#s(hammy-interval "Break" "" nil (lambda (hammy) (progn (ignore hammy) (let* ((val (car (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 3))))) (progn (ignore (consp val)) (let* ((x2 (car-safe val)) (x3 (cdr-safe val))) (progn (ignore (consp x3)) (let* ((x4 (car-safe x3)) (x5 (cdr-safe x3))) (progn (ignore (consp x5)) (let* ((x6 (car-safe x5)) (x7 (cdr-safe x5))) (progn (ignore (null x7)) (let ((_interval x2) (start x4) (end x6)) (let* ((work-seconds (float-time (time-subtract end start)))) (* work-seconds 0.33))))))))))))) ((lambda (hammy) (progn (ignore hammy) (let ((message (format "Starting break for %s." (ts-human-format-duration (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 8)))))) (hammy-announce hammy message) (hammy-notify hammy message))))) nil ((lambda (hammy) (if (listp (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 13))) nil (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (let* ((v hammy)) (aset v 13 (list (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 13))))))) (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (let* ((v hammy)) (aset v 13 (let* ((vlist (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (aref hammy 13)))) (if (memql --cl-cancel-reminder-- vlist) vlist (cons --cl-cancel-reminder-- vlist)))))) (let ((tail fns)) (while tail (let ((fn (car tail))) (funcall fn hammy) (setq tail (cdr tail))))) (let ((delay-secs (funcall --cl-duration-- delay))) (progn (or (progn (and (memq (type-of hammy) cl-struct-hammy-tags) t)) (signal 'wrong-type-argument (list 'hammy hammy))) (let* ((v hammy) (p (if (and nil (not (eq nil 'eq))) (assoc 'reminder (aref v 1

</details>

**Comment by alphapapa** [comment]
Try `(call-interactively #'hammy-next)`.  As long as only one hammy is running, that should work.

**Comment by Rickyfs** [comment]
It works, thanks
