### ISSUE TITLE
some images in mode-line not loading (pomodoro)

### ISSUE THREAD

**Issue by iantor** [alphapapa/hammy.el#16]
![image](https://github.com/alphapapa/hammy.el/assets/551061/f322c9e5-d802-4911-8c63-96a2b1b71d96)

Currently released emacs for windows, native comp enabled.

**Comment by alphapapa** [comment]
Hello Ian,

Those are not images but Unicode characters.  When Emacs displays them that way it indicates that you don't have a fontset configured that contains that character.  Here are some instructions that may help: https://github.com/alphapapa/ement.el#displaying-symbols-and-emojis
