### ISSUE TITLE
fixed issue with dbus notifications on windows emacs

### ISSUE THREAD

**Issue by iantor** [alphapapa/hammy.el#17]
I was having problems with dbus notifications (caused hammy not to start sometimes), got advice from IRC on disabling these, this worked when put at end of init.el

;; following to prevent issues with hammy, blocks dbus-style notifications

(fset 'notifications-notify 'ignore)

**Comment by alphapapa** [comment]
Hello Ian,

It's too bad that the notifications library still doesn't support Windows notifications.  In the meantime, you could do what you've done, or you could redefine those hammys to not call the `notify` function.  See, e.g. https://github.com/alphapapa/hammy.el/blob/cc885461c6f7cb4bb08e563f0324ebd2b415b17c/hammy.el#L1091
