### ISSUE TITLE
is there a hook for "Waiting for user to advance"?

### ISSUE THREAD

**Issue by bbigras** [alphapapa/hammy.el#18]
at 13:47:11, I would like to run my own command to send a notification to my watch to get back to work.

I would also like to use the same hook, or another one, to send me a notification to take a break if I'm not at my desk.

To test, I ran hammy-start, hammy-next and waited for the 5 minutes.

```
2023-10-18 13:42:06  Hammy (Move): Interval:None  Cycles:0  Message:"Starting..."
2023-10-18 13:42:06  Hammy (Move): Interval:💺 (45m)  Cycles:0  Message:"Interval started: 💺 (45m)"
2023-10-18 13:42:11  Hammy (Move): Interval:💺 (45m)  Cycles:0  Message:"Elapsed: 5s (-44m54s)"
2023-10-18 13:42:11  Hammy (Move): Interval:💺 (45m)  Cycles:0  Message:"Interval ended: 💺"
2023-10-18 13:42:11  Hammy (Move): Interval:🤸 (5m)  Cycles:0  Message:"Interval started: 🤸 (5m)"
2023-10-18 13:47:11  Hammy (Move): Interval:🤸 (5m)  Cycles:0  Message:"Waiting for user to advance..."
```

**Comment by alphapapa** [comment]
There's not a hook for that, no.  It would be hard to say how many hooks to add, where, and what their names should be, so we only define a few.  

Instead, users are encouraged to define their own hammys that do whatever they desire at the appropriate moments.  For example, the default `Move` timer reminds the user every 10 minutes that it's time to advance to the next interval, here: 

https://github.com/alphapapa/hammy.el/blob/cc885461c6f7cb4bb08e563f0324ebd2b415b17c/hammy.el#L1073-L1075

You'll note that the other interval in the same timer doesn't use the `remind` macro for its `advance` function: https://github.com/alphapapa/hammy.el/blob/cc885461c6f7cb4bb08e563f0324ebd2b415b17c/hammy.el#L1081-L1082

Anyway, you can set an interval's `advance` slot to a function that does whatever you like, including calling external commands.  The default timers don't do so, but a `run` macro (usable inside a `do` form) is provided to run commands; for example, this custom hammy uses it:

```el
(hammy-define "🐮"
    :documentation "Don't forget to stretch your legs."
    :intervals (list (interval :name "💺"
                               :duration "45 minutes"
                               :face 'font-lock-type-face
                               :before (do (announce "Whew!")
                                           (notify "Whew!"))
                               :advance (remind "10 minutes"
                                                (do (announce "Time to stretch your legs!")
                                                    (notify "Time to stretch your legs!")
                                                    (run (concat "aplay "
                                                                 (expand-file-name "~/Misc/Sounds/Mario/smw_yoshi_swallow.wav"))))))
                     (interval :name "🤸"
                               :duration "5 minutes"
                               :face 'font-lock-builtin-face
                               :before (do (announce "Mooove it!")
                                           (notify "Mooove it!"))
                               :advance (do (announce "Time for a sit-down...")
                                            (notify "Time for a sit-down...")
                                            (run (concat "aplay "
                                                         (expand-file-name "~/Misc/Sounds/Mario/smw_yoshi_tongue.wav")))))))
```

**Comment by bbigras** [comment]
Thanks!
