### ISSUE TITLE
Hammy idea: third-time technique (is it even possible)

### ISSUE THREAD

**Issue by meliache** [alphapapa/hammy.el#5]
The third-time technique is a variation on the pomodoro-technique that allows for work intervals to be flexible in length as long as the break time is then a fixed fraction of the work time. See: https://www.lesswrong.com/posts/RWu8eZqbwgB9zaerh/third-time-a-better-way-to-work. There is package extending `org-pomodoro` to follow this method, [org-pomodoro-third-time](https://github.com/telotortium/org-pomodoro-third-time), but it doesn't seem widely adopted yet and to me it feels like the package still needs a lot of work to be comfortable to use. I was thinking of contributing to that package to improve usability, but didn't get to it much yet. I'm thinking if doing that would be possible with hammy, which I just started using. I just requires keeping track of an internal bank-time which is then updated via the difference between the nominal duration of the previous work/break interval and its actual duration. Do you think this is feasible to implement as a hammy?

Further, I would be favour of implementing or documenting such a hammy somewhere. I don't think it's much more niche than the `flywheel` hammy, but the implementation might be too long for the readme. But maybe having it in the list pre-defined hammies might be nice anyway. Or we could have this as a snippet in the github wiki or in some hammy extensions package (e.g. named `hammy-extras` or `hammy-contrib`).

Some kind of collection of useful user-defined hammies might be useful anyway, when looking towards the future. Though I'm aware that the package is very early in development and you're also working on org-pomodoro integration, so if the interface/dsl is not really stable yet it might be too early for that.

**Comment by alphapapa** [comment]
Hi Michael,

I'm glad to hear from someone who's using this package, especially since it's so new.

Yes, this kind of flexibility is what I designed Hammy for.  For implementation, it shouldn't be too difficult.  After each interval is completed and the next interval's duration is about to be calculated, the previous interval's start and end times are recorded in the hammy's `history` slot, so the break interval's duration function simply needs to calculate the length of the previous work interval and apply the appropriate fraction to it.

This sounds like a widely useful type of timer, so I'd be glad to include it in the package by default.

**Comment by alphapapa** [comment]
I think that should do it.  Please let me know how that works for you.

**Comment by alphapapa** [comment]
> It works for me so far, but the implementation just taking into
> account the duration of the previous work period doesn't implement
> banking unused break time. I.e., if I end a break 5 minutes earlier
> than the suggested duration, the 5 minutes should be added to the next
> break, at least according to the [original
> proposal](https://www.lesswrong.com/posts/RWu8eZqbwgB9zaerh/third-time-a-better-way-to-work).

Oops, I missed that part.  The commit I just pushed should do that now.  Please let me know how it works for you.

**Comment by meliache** [comment]
Worked well today so far and I felt productive, though I have only used `hammy-start`/`-next`/`-stop` for now and didn't test whether other commands are well-behaved.

**Comment by alphapapa** [comment]
Thanks.
