### ISSUE TITLE
Error in emacs 29.0.50 (DOOM)

### ISSUE THREAD

**Issue by M1ndo** [alphapapa/hammy.el#8]
Hey, Hammy recently been causing errors in emacs 29.0.50.
```
Message: Symbol's value as variable is void
    Details: (hammy)
    Backtrace:
      (hammy-announce hammy "Starting work time.")
      (list (hammy-announce hammy "Starting work time.") (hammy-notify hammy "Starting work time."))
      (funcall --cl-interval-- :name "Work" :duration (funcall --cl-duration-- "25 minutes") :before (list (hammy-announce hammy "Starting work time.") (hammy-notify hammy "Starting work time.")) :advance (list (hammy-...
```
Full backtrace: https://0x0.st/o5NT.error

**Comment by alphapapa** [comment]
Hello,

Besides that Emacs 29 is not yet released, I see that you are using DOOM.  It seems likely that the package has not been installed correctly into DOOM.  So please try to reproduce the problem using a clean Emacs configuration, e.g. using https://github.com/alphapapa/with-emacs.sh.

**Comment by M1ndo** [comment]
Thanks for pointing that out, i've been using hammy for months and this issue never existed till recently.
Reinstalling Hammy fixed the issue.
